name: Anderes
description: Erstelle ein leeres Issue, falls keines der Vorlagen passend ist.
labels: ["t: Licht- & Tontechnik"]
title: "[Misc]: "

body:
  - type: markdown
    attributes:
      value: |
        Bitte gebe nach dem Pr채fix `[Misc]:` einen beschreibenden Titel f체r dein Issue an.
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      placeholder: ...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        Bitte f체ge passende Labels hinzu:
        
        _p: Priority (Priorit채t)  
        a: Assignee (zugewiesene Person)  
        t: Task Force (Arbeitsgruppe)_
